# On new Linux machines running Alacritty, make sure to run 
# `tmux source-file ~/.tmux.conf` to activate the config.
# Tmux + Ghostty on mac seemed can recognize the config automatically. 

set -g mouse on

# Status bar format
set -g status-right '%H:%M %d-%b-%y'

# Address vim mode switching delay (http://superuser.com/a/252717/65504)
set -s escape-time 0

# Increase scrollback buffer size from 2000 to 50000 lines
set -g history-limit 50000

# Easier and faster switching between next/prev window
bind C-p previous-window
bind C-n next-window

# Upgrade $TERM
set -g default-terminal "screen-256color"

