# On new Linux machines running Alacritty, make sure to run 
# `tmux source-file ~/.tmux.conf` to activate the config.
# Tmux + Ghostty on mac seemed can recognize the config automatically. 

set -g mouse on

